"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright (c) 2024, Neptune Labs.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
from ... import neptune_pb
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AttributeTypeAndPath(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _AttributeType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AttributeTypeEnumTypeWrapper(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[AttributeTypeAndPath._AttributeType.ValueType],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        PLACEHOLDER: AttributeTypeAndPath._AttributeType.ValueType
        COMPLEX: AttributeTypeAndPath._AttributeType.ValueType
        FLOAT: AttributeTypeAndPath._AttributeType.ValueType
        STRING: AttributeTypeAndPath._AttributeType.ValueType
        FILE: AttributeTypeAndPath._AttributeType.ValueType
        DATETIME: AttributeTypeAndPath._AttributeType.ValueType
        INT: AttributeTypeAndPath._AttributeType.ValueType
        BOOL: AttributeTypeAndPath._AttributeType.ValueType
        FLOAT_SERIES: AttributeTypeAndPath._AttributeType.ValueType
        STRING_SERIES: AttributeTypeAndPath._AttributeType.ValueType
        IMAGE_SERIES: AttributeTypeAndPath._AttributeType.ValueType
        STRING_SET: AttributeTypeAndPath._AttributeType.ValueType
        FILE_SET: AttributeTypeAndPath._AttributeType.ValueType
        GIT_REF: AttributeTypeAndPath._AttributeType.ValueType
        NOTEBOOK_REF: AttributeTypeAndPath._AttributeType.ValueType
        EXPERIMENT_STATE: AttributeTypeAndPath._AttributeType.ValueType

    class AttributeType(_AttributeType, metaclass=_AttributeTypeEnumTypeWrapper): ...
    PLACEHOLDER: AttributeTypeAndPath.AttributeType.ValueType
    COMPLEX: AttributeTypeAndPath.AttributeType.ValueType
    FLOAT: AttributeTypeAndPath.AttributeType.ValueType
    STRING: AttributeTypeAndPath.AttributeType.ValueType
    FILE: AttributeTypeAndPath.AttributeType.ValueType
    DATETIME: AttributeTypeAndPath.AttributeType.ValueType
    INT: AttributeTypeAndPath.AttributeType.ValueType
    BOOL: AttributeTypeAndPath.AttributeType.ValueType
    FLOAT_SERIES: AttributeTypeAndPath.AttributeType.ValueType
    STRING_SERIES: AttributeTypeAndPath.AttributeType.ValueType
    IMAGE_SERIES: AttributeTypeAndPath.AttributeType.ValueType
    STRING_SET: AttributeTypeAndPath.AttributeType.ValueType
    FILE_SET: AttributeTypeAndPath.AttributeType.ValueType
    GIT_REF: AttributeTypeAndPath.AttributeType.ValueType
    NOTEBOOK_REF: AttributeTypeAndPath.AttributeType.ValueType
    EXPERIMENT_STATE: AttributeTypeAndPath.AttributeType.ValueType
    TYPE_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    type: global___AttributeTypeAndPath.AttributeType.ValueType
    path: builtins.str

    def __init__(
        self, *, type: global___AttributeTypeAndPath.AttributeType.ValueType = ..., path: builtins.str = ...
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["path", b"path", "type", b"type"]) -> None: ...

global___AttributeTypeAndPath = AttributeTypeAndPath

@typing.final
class FieldData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FLOAT_ATOM_DATA_FIELD_NUMBER: builtins.int
    STRING_ATOM_DATA_FIELD_NUMBER: builtins.int
    DATETIME_ATOM_DATA_FIELD_NUMBER: builtins.int
    INT_ATOM_DATA_FIELD_NUMBER: builtins.int
    BOOL_ATOM_DATA_FIELD_NUMBER: builtins.int
    FLOAT_TIME_SERIES_DATA_FIELD_NUMBER: builtins.int
    STRING_TIME_SERIES_DATA_FIELD_NUMBER: builtins.int
    STRING_SET_DATA_FIELD_NUMBER: builtins.int
    float_atom_data: builtins.float
    string_atom_data: builtins.str
    int_atom_data: builtins.int
    bool_atom_data: builtins.bool

    @property
    def datetime_atom_data(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def float_time_series_data(self) -> global___FloatTimeSeriesData: ...
    @property
    def string_time_series_data(self) -> global___StringTimeSeriesData: ...
    @property
    def string_set_data(self) -> global___StringSetData: ...
    def __init__(
        self,
        *,
        float_atom_data: builtins.float = ...,
        string_atom_data: builtins.str = ...,
        datetime_atom_data: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        int_atom_data: builtins.int = ...,
        bool_atom_data: builtins.bool = ...,
        float_time_series_data: global___FloatTimeSeriesData | None = ...,
        string_time_series_data: global___StringTimeSeriesData | None = ...,
        string_set_data: global___StringSetData | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "bool_atom_data",
            b"bool_atom_data",
            "data",
            b"data",
            "datetime_atom_data",
            b"datetime_atom_data",
            "float_atom_data",
            b"float_atom_data",
            "float_time_series_data",
            b"float_time_series_data",
            "int_atom_data",
            b"int_atom_data",
            "string_atom_data",
            b"string_atom_data",
            "string_set_data",
            b"string_set_data",
            "string_time_series_data",
            b"string_time_series_data",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "bool_atom_data",
            b"bool_atom_data",
            "data",
            b"data",
            "datetime_atom_data",
            b"datetime_atom_data",
            "float_atom_data",
            b"float_atom_data",
            "float_time_series_data",
            b"float_time_series_data",
            "int_atom_data",
            b"int_atom_data",
            "string_atom_data",
            b"string_atom_data",
            "string_set_data",
            b"string_set_data",
            "string_time_series_data",
            b"string_time_series_data",
        ],
    ) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["data", b"data"]) -> (
        typing.Literal[
            "float_atom_data",
            "string_atom_data",
            "datetime_atom_data",
            "int_atom_data",
            "bool_atom_data",
            "float_time_series_data",
            "string_time_series_data",
            "string_set_data",
        ]
        | None
    ): ...

global___FieldData = FieldData

@typing.final
class FloatTimeSeriesData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SERIES_ID_FIELD_NUMBER: builtins.int
    LAST_STEP_FIELD_NUMBER: builtins.int
    LAST_TIMESTAMP_FIELD_NUMBER: builtins.int
    LAST_VALUE_FIELD_NUMBER: builtins.int
    FINITE_VALUE_COUNT_FIELD_NUMBER: builtins.int
    NAN_COUNT_FIELD_NUMBER: builtins.int
    SUM_FIELD_NUMBER: builtins.int
    SQUARE_SUM_FIELD_NUMBER: builtins.int
    MIN_FIELD_NUMBER: builtins.int
    MAX_FIELD_NUMBER: builtins.int
    series_id: builtins.bytes
    "RawSeriesId"
    last_value: builtins.float
    finite_value_count: builtins.int
    nan_count: builtins.int
    sum: builtins.float
    square_sum: builtins.float
    min: builtins.float
    max: builtins.float

    @property
    def last_step(self) -> neptune_pb.ingest.v1.common_pb2.Step: ...
    @property
    def last_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        series_id: builtins.bytes = ...,
        last_step: neptune_pb.ingest.v1.common_pb2.Step | None = ...,
        last_timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        last_value: builtins.float = ...,
        finite_value_count: builtins.int = ...,
        nan_count: builtins.int = ...,
        sum: builtins.float = ...,
        square_sum: builtins.float = ...,
        min: builtins.float = ...,
        max: builtins.float = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["last_step", b"last_step", "last_timestamp", b"last_timestamp"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "finite_value_count",
            b"finite_value_count",
            "last_step",
            b"last_step",
            "last_timestamp",
            b"last_timestamp",
            "last_value",
            b"last_value",
            "max",
            b"max",
            "min",
            b"min",
            "nan_count",
            b"nan_count",
            "series_id",
            b"series_id",
            "square_sum",
            b"square_sum",
            "sum",
            b"sum",
        ],
    ) -> None: ...

global___FloatTimeSeriesData = FloatTimeSeriesData

@typing.final
class StringTimeSeriesData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SERIES_ID_FIELD_NUMBER: builtins.int
    LAST_STEP_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    LAST_TIMESTAMP_FIELD_NUMBER: builtins.int
    LAST_VALUE_FIELD_NUMBER: builtins.int
    SUM_LENGTH_FIELD_NUMBER: builtins.int
    series_id: builtins.bytes
    "RawSeriesId"
    index: builtins.int
    last_value: builtins.str
    sum_length: builtins.int

    @property
    def last_step(self) -> neptune_pb.ingest.v1.common_pb2.Step: ...
    @property
    def last_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        series_id: builtins.bytes = ...,
        last_step: neptune_pb.ingest.v1.common_pb2.Step | None = ...,
        index: builtins.int = ...,
        last_timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        last_value: builtins.str = ...,
        sum_length: builtins.int = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["last_step", b"last_step", "last_timestamp", b"last_timestamp"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "index",
            b"index",
            "last_step",
            b"last_step",
            "last_timestamp",
            b"last_timestamp",
            "last_value",
            b"last_value",
            "series_id",
            b"series_id",
            "sum_length",
            b"sum_length",
        ],
    ) -> None: ...

global___StringTimeSeriesData = StringTimeSeriesData

@typing.final
class StringSetData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUES_FIELD_NUMBER: builtins.int

    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(self, *, values: collections.abc.Iterable[builtins.str] | None = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["values", b"values"]) -> None: ...

global___StringSetData = StringSetData
